import type { Metadata } from "next";
import { GeistSans as font } from "geist/font/sans";
import { cx } from "@/lib/utils";


import "@/styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"
      className={cx(
        'text-black bg-white dark:text-white dark:bg-[#111010]',
      )}
    >
      <body className={cx(font.className, "max-w-2xl flex flex-col")}>
        <main>{children}</main>
      </body>
    </html>
  );
}
